# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 'Build Web App'
description: 'Builds your web assets'
runs:
    using: 'composite'
    steps:
    - name: Checkout source
      shell: bash
      uses: actions/checkout@v4

    - name: Setup
      shell: bash
      uses: actions/setup-node@v4
      with:
        node-version: 18.x            

    - name: Install dependencies
      shell: bash
      run: |
        npm install

    - name: Build
      run: |
        npm run build